Add required projects in the staging job
It will fix following error coming in these jobs
https://review.rdoproject.org/zuul/builds?pipeline=github-post&skip=0
```
Error: Project github.com/openstack-k8s-operators/dataplane-operator does not have the default branch master
```

Signed-off-by: Chandan Kumar <chkumar@redhat.com>